<?php
// --------------------------------------------------------
//  This is a part of the Sparx Systems Pro Cloud Server.
//  Copyright (C) Sparx Systems Pty Ltd
//  All rights reserved.
//
//  This source code can be used only under terms and 
//  conditions of the accompanying license agreement.
// --------------------------------------------------------
	if  ( !isset($webea_page_parent_mainview) )
	{
		exit();
	}
	$sRootPath = dirname(__FILE__);
	require_once $sRootPath . '/globals.php';
	SafeStartSession();
	if (isset($_SESSION['authorized']) === false)
	{
		$sErrorMsg = _glt('Your session appears to have timed out');
		setResponseCode(440, $sErrorMsg);
		exit();
	}
	$aWatchList = array();
	$aWatchList = GetWatchListOptions();
	echo '<div id="main-watchlistconfig">';
	echo '	<div id="watchlist-config-layout">';
	echo '		<div id="watchlist-config-header">';
	echo '			<div id="watchlist-config-headerimage"><img src="images/spriteplaceholder.png" class="propsprite-watchlistconfig" alt=""/></div>';
	echo '			<div id="watchlist-config-headertext">' . _glt('Configure the Watchlist') . '</div>';
	echo '		</div>';
	echo '		<form class = "watchlist-config-form" role="form" onsubmit="OnFormRunWatchListConfig(event)">';
	echo '			<div id="watchlist-config-body">';
	echo '<table id="watchlist-config-table"><tbody>';
	echo '<tr class="watchlist-config-line">';
	echo '<td colspan="2" class="watchlist-config-option-hdr">' . _glt('Activity Period') . '</td>';
	echo '</tr>';
	$iDays = SafeGetArrayItem1Dim($aWatchList, 'period');
	echo '<tr class="watchlist-config-line">';
	echo '<td class="watchlist-config-label2 field-label-vert-align-top">' . _glt('Number of days') . '</td>';
	echo '<td class="watchlist-config-field"><input class="watchlist-config-period-field" id="wlc-period" name="period" type="number" value="' . strval($iDays) . '" min="0" max="999" step="1" maxlength="3" onblur="OnIntegerFieldLostFocus(\'wlc-period\')"></td>';
	echo '</tr>';
	echo '<tr class="watchlist-config-line"><td colspan="3" class="watchlist-config-option-hdr">&nbsp;</td></tr>';
	echo '<tr class="watchlist-config-line">';
	echo '<td colspan="2" class="watchlist-config-option-hdr">' . _glt('Recent') . '</td>';
	echo '</tr>';
	echo '<tr class="watchlist-config-line">';
	echo '<td class="watchlist-config-label field-label-vert-align-top">' . _glt('Discussions') . '</td>';
	echo '<td class="watchlist-config-field"><input type="checkbox" id="wlc-recentdiscuss" name="recentdiscuss" ' . IsChecked($aWatchList, 'recentdiscuss') . '>&nbsp;</td>';
	echo '</tr>';
	echo '<tr class="watchlist-config-line">';
	echo '<td class="watchlist-config-label field-label-vert-align-top">' . _glt('Active reviews') . '</td>';
	echo '<td class="watchlist-config-field"><input type="checkbox" id="wlc-recentreview" name="recentreview" ' . IsChecked($aWatchList, 'recentreview') . '>&nbsp;</td>';
	echo '</tr>';
	echo '<tr class="watchlist-config-line">';
	echo '<td class="watchlist-config-label field-label-vert-align-top">' . _glt('Modified diagrams') . '</td>';
	echo '<td class="watchlist-config-field"><input type="checkbox" id="wlc-recentdiag" name="recentdiag" ' . IsChecked($aWatchList, 'recentdiag') . '>&nbsp;</td>';
	echo '</tr>';
	echo '<tr class="watchlist-config-line">';
	echo '<td class="watchlist-config-label field-label-vert-align-top">' . _glt('Modified elements') . '</td>';
	echo '<td class="watchlist-config-field"><input type="checkbox" id="wlc-recentelem" name="recentelem" ' . IsChecked($aWatchList, 'recentelem') . '>&nbsp;</td>';
	echo '</tr>';
	echo '<tr class="watchlist-config-line"><td colspan="3" class="watchlist-config-option-hdr">&nbsp;</td></tr>';
	echo '<tr class="watchlist-config-line">';
	echo '<td colspan="2" class="watchlist-config-option-hdr">' . _glt('Resource Allocations') . '&nbsp;&nbsp;&nbsp;<img alt="" src="images/spriteplaceholder.png" class="propsprite-resalloc"/></td>';
	echo '</tr>';
	echo '<tr class="watchlist-config-line">';
	echo '<td class="watchlist-config-label field-label-vert-align-top">' . _glt('Active') . '</td>';
	echo '<td class="watchlist-config-field"><input type="checkbox" id="wlc-resallocactive" name="resallocactive" ' . IsChecked($aWatchList, 'resallocactive') . '>&nbsp;</td>';
	echo '</tr>';
	echo '<tr class="watchlist-config-line">';
	echo '<td class="watchlist-config-label field-label-vert-align-top">' . _glt('Ending today') . '</td>';
	echo '<td class="watchlist-config-field"><input type="checkbox" id="wlc-resalloctoday" name="resalloctoday" ' . IsChecked($aWatchList, 'resalloctoday') . '>&nbsp;</td>';
	echo '</tr>';
	echo '<tr class="watchlist-config-line">';
	echo '<td class="watchlist-config-label field-label-vert-align-top">' . _glt('Overdue') . '</td>';
	echo '<td class="watchlist-config-field"><input type="checkbox" id="wlc-resallocoverdue" name="resallocoverdue" ' . IsChecked($aWatchList, 'resallocoverdue') . '>&nbsp;</td>';
	echo '</tr>';
	echo '<tr class="watchlist-config-line"><td colspan="3" class="watchlist-config-option-hdr">&nbsp;</td></tr>';
	echo '<tr class="watchlist-config-line">';
	echo '<td colspan="2" class="watchlist-config-option-hdr">' . _glt('Tests') . '&nbsp;&nbsp;&nbsp;<img alt="" src="images/spriteplaceholder.png" class="propsprite-test"/></td>';
	echo '</tr>';
	echo '<tr class="watchlist-config-line">';
	echo '<td class="watchlist-config-label field-label-vert-align-top">' . _glt('Recently passed') . '</td>';
	echo '<td class="watchlist-config-field"><input type="checkbox" id="wlc-testrecentpass" name="testrecentpass" ' . IsChecked($aWatchList, 'testrecentpass') . '>&nbsp;</td>';
	echo '</tr>';
	echo '<tr class="watchlist-config-line">';
	echo '<td class="watchlist-config-label field-label-vert-align-top">' . _glt('Recently failed') . '</td>';
	echo '<td class="watchlist-config-field"><input type="checkbox" id="wlc-testrecentfail" name="testrecentfail" ' . IsChecked($aWatchList, 'testrecentfail') . '>&nbsp;</td>';
	echo '</tr>';
	echo '<tr class="watchlist-config-line">';
	echo '<td class="watchlist-config-label field-label-vert-align-top">' . _glt('Recently deferred') . '</td>';
	echo '<td class="watchlist-config-field"><input type="checkbox" id="wlc-testrecentdefer" name="testrecentdefer" ' . IsChecked($aWatchList, 'testrecentdefer') . '>&nbsp;</td>';
	echo '</tr>';
	echo '<tr class="watchlist-config-line">';
	echo '<td class="watchlist-config-label field-label-vert-align-top">' . _glt('Recently not checked') . '</td>';
	echo '<td class="watchlist-config-field"><input type="checkbox" id="wlc-testrecentnotchk" name="testrecentnotchk" ' . IsChecked($aWatchList, 'testrecentnotchk') . '>&nbsp;</td>';
	echo '</tr>';
	echo '<tr class="watchlist-config-line">';
	echo '<td class="watchlist-config-label field-label-vert-align-top">' . _glt('Not run') . '</td>';
	echo '<td class="watchlist-config-field"><input type="checkbox" id="wlc-testnotrun" name="testnotrun" ' . IsChecked($aWatchList, 'testnotrun') . '>&nbsp;</td>';
	echo '</tr>';
	echo '<tr class="watchlist-config-line"><td colspan="3" class="watchlist-config-option-hdr">&nbsp;</td></tr>';
	echo '<tr class="watchlist-config-line">';
	echo '<td colspan="2" class="watchlist-config-option-hdr">' . _glt('Changes') . '&nbsp;&nbsp;&nbsp;<img alt="" src="images/spriteplaceholder.png" class="propsprite-change"/></td>';
	echo '</tr>';
	echo '<tr class="watchlist-config-line">';
	echo '<td class="watchlist-config-label field-label-vert-align-top">' . _glt('Verified') . '</td>';
	echo '<td class="watchlist-config-field"><input type="checkbox" id="wlc-changeverified" name="changeverified" ' . IsChecked($aWatchList, 'changeverified') . '>&nbsp;</td>';
	echo '</tr>';
	echo '<tr class="watchlist-config-line">';
	echo '<td class="watchlist-config-label field-label-vert-align-top">' . _glt('Recently requested') . '</td>';
	echo '<td class="watchlist-config-field"><input type="checkbox" id="wlc-changerequested" name="changerequested" ' . IsChecked($aWatchList, 'changerequested') . '>&nbsp;</td>';
	echo '</tr>';
	echo '<tr class="watchlist-config-line">';
	echo '<td class="watchlist-config-label field-label-vert-align-top">' . _glt('Recently completed') . '</td>';
	echo '<td class="watchlist-config-field"><input type="checkbox" id="wlc-changecompleted" name="changecompleted" ' . IsChecked($aWatchList, 'changecompleted') . '>&nbsp;</td>';
	echo '</tr>';
	echo '<tr class="watchlist-config-line">';
	echo '<td class="watchlist-config-label field-label-vert-align-top">' . _glt('New') . '</td>';
	echo '<td class="watchlist-config-field"><input type="checkbox" id="wlc-changenew" name="changenew" ' . IsChecked($aWatchList, 'changenew') . '>&nbsp;</td>';
	echo '</tr>';
	echo '<tr class="watchlist-config-line">';
	echo '<td class="watchlist-config-label field-label-vert-align-top">' . _glt('Incomplete') . '</td>';
	echo '<td class="watchlist-config-field"><input type="checkbox" id="wlc-changeincomplete" name="changeincomplete" ' . IsChecked($aWatchList, 'changeincomplete') . '>&nbsp;</td>';
	echo '</tr>';
	echo '<tr class="watchlist-config-line"><td colspan="3" class="watchlist-config-option-hdr">&nbsp;</td></tr>';
	echo '<tr class="watchlist-config-line">';
	echo '<td colspan="2" class="watchlist-config-option-hdr">' . _glt('Defects') . '&nbsp;&nbsp;&nbsp;<img alt="" src="images/spriteplaceholder.png" class="propsprite-defect"/></td>';
	echo '</tr>';
	echo '<tr class="watchlist-config-line">';
	echo '<td class="watchlist-config-label field-label-vert-align-top">' . _glt('Verified') . '</td>';
	echo '<td class="watchlist-config-field"><input type="checkbox" id="wlc-defectverified" name="defectverified" ' . IsChecked($aWatchList, 'defectverified') . '>&nbsp;</td>';
	echo '</tr>';
	echo '<tr class="watchlist-config-line">';
	echo '<td class="watchlist-config-label field-label-vert-align-top">' . _glt('Recently reported') . '</td>';
	echo '<td class="watchlist-config-field"><input type="checkbox" id="wlc-defectrequested" name="defectrequested" ' . IsChecked($aWatchList, 'defectrequested') . '>&nbsp;</td>';
	echo '</tr>';
	echo '<tr class="watchlist-config-line">';
	echo '<td class="watchlist-config-label field-label-vert-align-top">' . _glt('Recently resolved') . '</td>';
	echo '<td class="watchlist-config-field"><input type="checkbox" id="wlc-defectcompleted" name="defectcompleted" ' . IsChecked($aWatchList, 'defectcompleted') . '>&nbsp;</td>';
	echo '</tr>';
	echo '<tr class="watchlist-config-line">';
	echo '<td class="watchlist-config-label field-label-vert-align-top">' . _glt('New') . '</td>';
	echo '<td class="watchlist-config-field"><input type="checkbox" id="wlc-defectnew" name="defectnew" ' . IsChecked($aWatchList, 'defectnew') . '>&nbsp;</td>';
	echo '</tr>';
	echo '<tr class="watchlist-config-line">';
	echo '<td class="watchlist-config-label field-label-vert-align-top">' . _glt('Incomplete') . '</td>';
	echo '<td class="watchlist-config-field"><input type="checkbox" id="wlc-defectincomplete" name="defectincomplete" ' . IsChecked($aWatchList, 'defectincomplete') . '>&nbsp;</td>';
	echo '</tr>';
	echo '<tr class="watchlist-config-line"><td colspan="3" class="watchlist-config-option-hdr">&nbsp;</td></tr>';
	echo '<tr class="watchlist-config-line">';
	echo '<td colspan="2" class="watchlist-config-option-hdr">' . _glt('Issues') . '&nbsp;&nbsp;&nbsp;<img alt="" src="images/spriteplaceholder.png" class="propsprite-issue"/></td>';
	echo '</tr>';
	echo '<tr class="watchlist-config-line">';
	echo '<td class="watchlist-config-label field-label-vert-align-top">' . _glt('Verified') . '</td>';
	echo '<td class="watchlist-config-field"><input type="checkbox" id="wlc-issueverified" name="issueverified" ' . IsChecked($aWatchList, 'issueverified') . '>&nbsp;</td>';
	echo '</tr>';
	echo '<tr class="watchlist-config-line">';
	echo '<td class="watchlist-config-label field-label-vert-align-top">' . _glt('Recently reported') . '</td>';
	echo '<td class="watchlist-config-field"><input type="checkbox" id="wlc-issuerequested" name="issuerequested" ' . IsChecked($aWatchList, 'issuerequested') . '>&nbsp;</td>';
	echo '</tr>';
	echo '<tr class="watchlist-config-line">';
	echo '<td class="watchlist-config-label field-label-vert-align-top">' . _glt('Recently resolved') . '</td>';
	echo '<td class="watchlist-config-field"><input type="checkbox" id="wlc-issuecompleted" name="issuecompleted" ' . IsChecked($aWatchList, 'issuecompleted') . '>&nbsp;</td>';
	echo '</tr>';
	echo '<tr class="watchlist-config-line">';
	echo '<td class="watchlist-config-label field-label-vert-align-top">' . _glt('New') . '</td>';
	echo '<td class="watchlist-config-field"><input type="checkbox" id="wlc-issuenew" name="issuenew" ' . IsChecked($aWatchList, 'issuenew') . '>&nbsp;</td>';
	echo '</tr>';
	echo '<tr class="watchlist-config-line">';
	echo '<td class="watchlist-config-label field-label-vert-align-top">' . _glt('Incomplete') . '</td>';
	echo '<td class="watchlist-config-field"><input type="checkbox" id="wlc-issueincomplete" name="issueincomplete" ' . IsChecked($aWatchList, 'issueincomplete') . '>&nbsp;</td>';
	echo '</tr>';
	echo '<tr class="watchlist-config-line"><td colspan="3" class="watchlist-config-option-hdr">&nbsp;</td></tr>';
	echo '<tr class="watchlist-config-line">';
	echo '<td colspan="2" class="watchlist-config-option-hdr">' . _glt('Tasks') . '&nbsp;&nbsp;&nbsp;<img alt="" src="images/spriteplaceholder.png" class="propsprite-task"/></td>';
	echo '</tr>';
	echo '<tr class="watchlist-config-line">';
	echo '<td class="watchlist-config-label field-label-vert-align-top">' . _glt('Verified') . '</td>';
	echo '<td class="watchlist-config-field"><input type="checkbox" id="wlc-taskverified" name="taskverified" ' . IsChecked($aWatchList, 'taskverified') . '>&nbsp;</td>';
	echo '</tr>';
	echo '<tr class="watchlist-config-line">';
	echo '<td class="watchlist-config-label field-label-vert-align-top">' . _glt('Recently requested') . '</td>';
	echo '<td class="watchlist-config-field"><input type="checkbox" id="wlc-taskrequested" name="taskrequested" ' . IsChecked($aWatchList, 'taskrequested') . '>&nbsp;</td>';
	echo '</tr>';
	echo '<tr class="watchlist-config-line">';
	echo '<td class="watchlist-config-label field-label-vert-align-top">' . _glt('Recently completed') . '</td>';
	echo '<td class="watchlist-config-field"><input type="checkbox" id="wlc-taskcompleted" name="taskcompleted" ' . IsChecked($aWatchList, 'taskcompleted') . '>&nbsp;</td>';
	echo '</tr>';
	echo '<tr class="watchlist-config-line">';
	echo '<td class="watchlist-config-label field-label-vert-align-top">' . _glt('New') . '</td>';
	echo '<td class="watchlist-config-field"><input type="checkbox" id="wlc-tasknew" name="tasknew" ' . IsChecked($aWatchList, 'tasknew') . '>&nbsp;</td>';
	echo '</tr>';
	echo '<tr class="watchlist-config-line">';
	echo '<td class="watchlist-config-label field-label-vert-align-top">' . _glt('Incomplete') . '</td>';
	echo '<td class="watchlist-config-field"><input type="checkbox" id="wlc-taskincomplete" name="taskincomplete" ' . IsChecked($aWatchList, 'taskincomplete') . '>&nbsp;</td>';
	echo '</tr>';
	echo '<tr class="watchlist-config-line"><td colspan="3" class="watchlist-config-option-hdr">&nbsp;</td></tr>';
	echo '<tr class="watchlist-config-line">';
	echo '<td colspan="2" class="watchlist-config-option-hdr">' . _glt('Events') . '&nbsp;&nbsp;&nbsp;<img alt="" src="images/spriteplaceholder.png" class="propsprite-event"/></td>';
	echo '</tr>';
	echo '<tr class="watchlist-config-line">';
	echo '<td class="watchlist-config-label field-label-vert-align-top">' . _glt('Recently requested') .'</td>';
	echo '<td class="watchlist-config-field"><input type="checkbox" id="wlc-eventrequested" name="eventrequested" ' . IsChecked($aWatchList, 'eventrequested') . '>&nbsp;</td>';
	echo '</tr>';
	echo '<tr class="watchlist-config-line">';
	echo '<td class="watchlist-config-label field-label-vert-align-top">' . _glt('High Priority') . '</td>';
	echo '<td class="watchlist-config-field"><input type="checkbox" id="wlc-eventnew" name="eventnew" ' . IsChecked($aWatchList, 'eventnew') . '>&nbsp;</td>';
	echo '</tr>';
	echo '<tr class="watchlist-config-line">';
	echo '<td class="watchlist-config-label field-label-vert-align-top">' . _glt('Incomplete') . '</td>';
	echo '<td class="watchlist-config-field"><input type="checkbox" id="wlc-eventincomplete" name="eventincomplete" ' . IsChecked($aWatchList, 'eventincomplete') . '>&nbsp;</td>';
	echo '</tr>';
	echo '<tr class="watchlist-config-line"><td colspan="3" class="watchlist-config-option-hdr">&nbsp;</td></tr>';
	echo '<tr class="watchlist-config-line">';
	echo '<td colspan="2" class="watchlist-config-option-hdr">' . _glt('Decisions') . '&nbsp;&nbsp;&nbsp;<img alt="" src="images/spriteplaceholder.png" class="propsprite-decision"/></td>';
	echo '</tr>';
	echo '<tr class="watchlist-config-line">';
	echo '<td class="watchlist-config-label field-label-vert-align-top">' . _glt('Verified') . '</td>';
	echo '<td class="watchlist-config-field"><input type="checkbox" id="wlc-decisionverified" name="decisionverified" ' . IsChecked($aWatchList, 'decisionverified') . '>&nbsp;</td>';
	echo '</tr>';
	echo '<tr class="watchlist-config-line">';
	echo '<td class="watchlist-config-label field-label-vert-align-top">' . _glt('Recently requested') . '</td>';
	echo '<td class="watchlist-config-field"><input type="checkbox" id="wlc-decisionrequested" name="decisionrequested" ' . IsChecked($aWatchList, 'decisionrequested') . '>&nbsp;</td>';
	echo '</tr>';
	echo '<tr class="watchlist-config-line">';
	echo '<td class="watchlist-config-label field-label-vert-align-top">' . _glt('Recently completed') . '</td>';
	echo '<td class="watchlist-config-field"><input type="checkbox" id="wlc-decisioncompleted" name="decisioncompleted" ' . IsChecked($aWatchList, 'decisioncompleted') . '>&nbsp;</td>';
	echo '</tr>';
	echo '<tr class="watchlist-config-line">';
	echo '<td class="watchlist-config-label field-label-vert-align-top">' . _glt('New') . '</td>';
	echo '<td class="watchlist-config-field"><input type="checkbox" id="wlc-decisionnew" name="decisionnew" ' . IsChecked($aWatchList, 'decisionnew') . '>&nbsp;</td>';
	echo '</tr>';
	echo '<tr class="watchlist-config-line">';
	echo '<td class="watchlist-config-label field-label-vert-align-top">' . _glt('Incomplete') . '</td>';
	echo '<td class="watchlist-config-field"><input type="checkbox" id="wlc-decisionincomplete" name="decisionincomplete" ' . IsChecked($aWatchList, 'decisionincomplete') . '>&nbsp;</td>';
	echo '</tr>';
	if ( count($_COOKIE) == 0 )
	{
		echo '<tr class="watchlist-config-line">';
		echo '<td colspan="2">' . _glt('Warning: Browser has no cookies') . '</td>';
		echo '</tr>';
	}
	echo '</tbody></table>';
	echo '	</div>';
	echo '	<div id="watchlist-config-footer">';
	echo '	  <span id="watchlist-config-selectall" class="w3-link" onclick="OnSetAllCheckboxes(\'true\')">Select All</span>';
	echo '	  <span id="watchlist-config-deselectall" class="w3-link" onclick="OnSetAllCheckboxes(\'false\')">Deselect All</span>';
	echo '	  <span>';
	echo '	    <div class="webea-main-styled-button watchlist-config-submit" onclick="OnFormRunWatchListConfig(event)">';
	echo '	      <div class="save-button-icon"></div>';
	echo '	      <div id="watchlist-save-button-text" class="webea-styled-button-text">' . _glt('Save') . '</div>';
	echo '	    </div>';
	echo '	  </span>';
	echo '	</div>';
	echo '</form>';
	echo '</div>';
	echo '</div>';
	function IsChecked($a, $sOption)
	{
		$sReturn = '';
		$i = SafeGetArrayItem1DimInt($a, $sOption);
		if ( $i == 1 )
		{
			$sReturn = ' checked ';
		}
		return $sReturn;
	}
?>